function displayQuote() {
    var anyQuote = [
    "There’s nothing wrong with having a tree as a friend.",
    "Anything that you believe you can do strong enough, you can do. Anything. As long as you believe.",
    "We don’t make mistakes. We have happy accidents.",
    "I think there’s an artist hidden at the bottom of every single one of us.",
    "You too can paint almighty pictures.",
    "No pressure. Just relax and watch it happen.",
    "It’s so important to do something every day that will make you happy.",
    "Look around. Look at what we have. Beauty is everywhere – you only have to look to see it.",
    "Talent is a pursued interest. Anything that you’re willing to practice, you can do.",
    "You need the dark in order to show the light.",
    "Nothing in the world breeds success like success, even if you start with the smallest amount.",
    "If we’re going to have animals around we all have to be concerned about them and take care of them.",
    "I think there’s an artist hidden at the bottom of every single one of us.",
    "Every day is a good day when you paint.",
    "Everyone needs a friend.",
    "Don’t forget to tell these special people in your life just how special they are to you.",
    "Didn’t you know you had that much power? You can move mountains. You can do anything.",
    "Just let go — and fall like a little waterfall.",
    "You can do anything you want to do. This is your world.",
    "However you think it should be, that’s exactly how it should be.",
    "You can have anything you want in the world — once you help everyone around you get what they want.",
    "In nature, dead trees are just as normal as live trees.",
    "Remember how free clouds are. They just lay around in the sky all day long.",
    "We don’t really know where this goes — and I’m not sure we really care.",
    "You can do anything here — the only prerequisite is that it makes you happy.",
    "Go out on a limb — that’s where the fruit is.",
    "Anytime you learn, you gain.",
    "It’s life. It’s interesting. It’s fun.",
    "Let your imagination run wild. That’s what life is all about.",
    "Trees are like people. They all have a few flaws in them.",
    "When you get a little challenge in your life you tend to enjoy it.",
    "Even a little tree will grow up to be a big tree. All it needs is water, sunshine and love - the same as all of us.",
    "It is my world and everything in my world is happy.",
    "Let’s be brave - because we can do anything.",
    "The joy in life comes from doing your own thing.",
    "Go outside and make friends with a tree.",
    "All you have to do is decide and then let the rest happen.",
    "If you look into the clouds long enough, you’ll find what you’re looking for.",
    "You just have to find what works for you.",
    "Once you get over the fear, you’ll be amazed at what you can do.",
    "Of course you can do that. You can do anything.",
    "If you have to do something over again, it doesn’t mean you’re bad, it just means you’re normal.",
    "Let your imagination take you anywhere you want to go.",
    "There’s no good or bad. There’s just what makes you happy.",
    "Anything that you can visualize in your mind, you can do.",
    "Sometimes you can amaze yourself.",
    "All you have to do is realize there are no boundaries here.",
    "You can do anything in this life. As long as you believe you can.",
    "No one has ever been hurt by having too many friends.",
    "Everybody has their own ideas, and that’s the way it should be.",
    "The only rule is that you should enjoy this.",
    "All it takes is just a little change of perspective and you begin to see a whole new world.",
    "Everyone is going to see things differently - and that’s the way it should be.",
    "When you do it your way you can go anywhere you choose.",
    "You can create beautiful things - but you have to see them in your mind first.",
    "Don’t be afraid to make these big decisions. Once you start, they sort of just make themselves.",
    "You’re meant to have fun in life.",
    "In life you need colors.",
    "Pretend you’re water. Just floating without any effort. Having a good day.",
    "When things happen - enjoy them. They’re little gifts.",
    "It’s amazing what you can do with a little love in your heart.",
    "You can do anything your heart can imagine.",
    "We have no limits to our world. We’re only limited by our imagination.",
    "The least little bit can do so much.",
    "If you don’t like it - change it. It’s your world.",
    "There is immense joy in just watching - watching all the little creatures in nature.",
    "Life is too short to be alone, too precious. Share it with a friend.",
    "Dead trees are also a part of nature.",
    "Sometimes you learn more from your mistakes than you do from your masterpieces.",
    "You can create anything that makes you happy.",
    "Everything’s not great in life, but we can still find beauty in it.",
    "Don’t hurry. Take your time and enjoy.",
    "You’re the greatest thing that has ever been or ever will be. You’re special. You’re so very special.",
    "There is no right or wrong - as long as it makes you happy and doesn’t hurt anyone.",
    "Everyone needs a friend. Friends are the most valuable things in the world.",
    "We each see the world in our own way. That’s what makes it such a special place.",
    "We don’t laugh because we feel good, we feel good because we laugh.",
    "Believe that you can do it, cause you can do it. You can do it.",
    "Isn’t it fantastic that you can change your mind and create all these happy things?",
    "They say everything looks better with odd numbers of things. But sometimes I put even numbers — just to upset the critics.",
    "I don’t intimidate anyone. Instead, I try to get people to believe in themselves.",
    "It’s hard to see things when you are too close. Take a step back and look.",
    "Gotta have a little sadness once in awhile so you know when the good times come.",
    "Exercising the imagination, experimenting with talents, being creative; these things, to me, are truly the windows to your soul.",
    "Don't get upset if something didn't go right. You learn from mistakes.",
    "Anything that happens, you can learn to use it and make something out of it.",
    "Nothing will teach you more than just experimenting. Do as many different things as you have the nerve to do. Go for it.",
    "Any time you make a mistake, before you get upset with it, look at it. Sometimes those mistakes turn out to be the best learning devices we have."
    ];
    
    var randomQuote = Math.floor(Math.random() * anyQuote.length);
    document.getElementById("randomquote").innerHTML = anyQuote[randomQuote];
}